### PR TITLE
Corrections for Vue App

### PR DESCRIPTION
**Pull request by kilakewe**
Add keys for each v-for
Replace `membership_data["address"]` with `membership_data.address`
Replace Country input with Country selector using ISO-3166-1 value (API seems to require this format)
Add check for bad JSON on `membership_data.address` for new accounts (This was what caused my issues)
Add const on some objects that were being defined for the first time.
Add console logging for axios error
Changed some object functions to be practice format. 
Replaced validation warning error definitions (missing const/let)
Add optional chaining to mebership_data properties in case they had not been defined.
Removed unused response variable

### CODE REVIEW

**Comment by kilakewe** [comment]
@hblankenship following up from our email convo - I found that there was an issue with the data coming from the API. It had Non-Compliant JSON set as the address, and I suspect this is being set by default somewhere in the API layer when a new account is created. 

I've cleaned up the code correcting a lot of best practices that weren't in place to also help ensure maintainability in the future.  

Lastly, I've also changed the country input to a country selector that provides the 2 character country code. When making calls to the API, it liked only the exact country name or the two-character code. So I've added a country dropdown to make it less prone to issues.

**Comment by hblankenship** [comment]
Thanks for this. I will go over it as soon as I can.

**Comment by hblankenship** [comment]
I have not been able to verify this as the :key attributes are playing havoc.... See screenshot below.
In the Personal Information panel, I removed the :key attribute and it works. The lower panel still has the key attributes. Ideas?

image

**Comment by kilakewe** [comment]
> I have not been able to verify this as the :key attributes are playing havoc.... See screenshot below. In the Personal Information panel, I removed the :key attribute and it works. The lower panel still has the key attributes. Ideas?
> 
> image

It may be something parsing it that doesn't like the back ticks. I've swapped them out for single quotes. Let's see if that works.

**Comment by hblankenship** [comment]
> > I have not been able to verify this as the :key attributes are playing havoc.... See screenshot below. In the Personal Information panel, I removed the :key attribute and it works. The lower panel still has the key attributes. Ideas?
> > image
> 
> It may be something parsing it that doesn't like the back ticks. I've swapped them out for single quotes. Let's see if that works.

So, same thing. If I change :key= to key= then it works. Doesn't seem to like the colon before the key attribute. But then does it really work the same?

**Comment by hblankenship** [comment]
Perhaps, as long as it still works, remove the key hints? I do not think they are needed in this case.

**Comment by kilakewe** [comment]
Vue may throw a couple of warnings about removing them but if it works, it works. 

One thing I didn’t check - what version of vue is being loaded?

Regards,

Gage Keenan

On 5/02/2022, at 8:40 AM, Harold Blankenship ***@***.***> wrote:

﻿
Perhaps, as long as it still works, remove the key hints? I do not think they are needed in this case.

**Comment by hblankenship** [comment]
> Vue may throw a couple of warnings about removing them but if it works, it works. One thing I didn’t check - what version of vue is being loaded? Regards, Gage Keenan On 5/02/2022, at 8:40 AM, Harold Blankenship ***@***.***> wrote: ﻿ Perhaps, as long as it still works, remove the key hints? I do not think they are needed in this case. — Reply to this email directly, view it on GitHub, or unsubscribe. You are receiving this because you authored the thread.

2.16.14 from https://unpkg.com/vue

**Comment by kilakewe** [comment]
Okay, so it’s not the vue package. It’s quite odd. 

I say less do take out the keys for no.

I’ll see if there’s a better strategy like including the vue app as a complied app instead. 

Regards,

Gage Keenan

On 5/02/2022, at 10:31 AM, Harold Blankenship ***@***.***> wrote:

﻿
Vue may throw a couple of warnings about removing them but if it works, it works. One thing I didn’t check - what version of vue is being loaded? Regards, Gage Keenan On 5/02/2022, at 8:40 AM, Harold Blankenship @.***> wrote: ﻿ Perhaps, as long as it still works, remove the key hints? I do not think they are needed in this case. — Reply to this email directly, view it on GitHub, or unsubscribe. You are receiving this because you authored the thread.

2.16.14 from https://unpkg.com/vue

**Comment by hblankenship** [comment]
It seems that unpkg has now changed the default Vue to 3 instead of 2. The load for unpkg needs to be changed to https://unpkg.com/vue@2/dist/vue.min.js

This could be confusing the issue.

**Comment by kilakewe** [comment]
That makes a lot of sense. I wrote the changes in a Vue 2 environment. Did it stop throwing errors when you switch to the Vue 2 script?

**Comment by hblankenship** [comment]
> That makes a lot of sense. I wrote the changes in a Vue 2 environment. Did it stop throwing errors when you switch to the Vue 2 script?

No, the keys still need to be removed. Can you do that and submit and I will merge these changes?

**Comment by hblankenship** [comment]
Going to merge and then fix these as the member portal does not work currently.

**Pull request merged**
